#!/usr/bin/env snakemake

import subprocess as subp
import pandas as pd
import metapi


shell.executable("bash")

include: "fingerprint.smk"

rule all:
    input:
        rules.cami_fingerprint_all.input
